FROM imazen/folioxml:latest

WORKDIR /app

#Update source code
COPY pom.xml .
COPY core ./core
COPY commandline ./commandline
COPY diff_match_patch ./diff_match_patch
COPY contrib ./contrib
# Add other module directories if they are part of the build

RUN echo "Building application..."
RUN mvn package assembly:single -pl commandline -am -U -B -fae

# Define a mount point for user data (config, input, output)
VOLUME /data

# Copy only the built fat JAR from the builder stage.
RUN cp /app/commandline/target/folioxml-commandline-jar-with-dependencies.jar /app/folioxml.jar

# Set the entrypoint to run the application
ENTRYPOINT ["java", "-jar", "/app/folioxml.jar"]
